name: Canci
favicon: null
layout_spectrum: 0.3301
typography_spectrum: 0.1766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff7'
    - '#0fbdb3'
    - '#1e0930'
    - '#ff4a2b'
    - '#894b50'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
